### ISSUE TITLE
Modifications to the EUI entry point from US#2

### ISSUE THREAD

**Issue by LibbyUX** [x-atlas-consortia/hra-apps#18]
# Modifications to the EUI entry point from US#2
### Current Implementation
![image](https://github.com/x-atlas-consortia/hra-apps/assets/97060856/fa49dd2f-eec2-4da9-8e80-381551fa6197)

### Approved UI Specification
![image](https://github.com/x-atlas-consortia/hra-apps/assets/97060856/97678a4c-9278-4c61-b6f9-f8ee98cea1d8)

## Figma Resources
- Design File: [HRA Apps Feb 2024 Modifications](https://www.figma.com/file/sASmFJEO5Usd3YS0IXNMBQ/Applications-of-the-Human-Reference-Atlas?type=design&node-id=362-4351&mode=design&t=mRfBULLR11dUu5gu-4)
- Design File: [Similar RUI Locations node](https://www.figma.com/file/sASmFJEO5Usd3YS0IXNMBQ/Applications-of-the-Human-Reference-Atlas?type=design&node-id=366-4383&mode=design&t=mRfBULLR11dUu5gu-4)
- Design File: [EUI Modal with Back Button](https://www.figma.com/file/sASmFJEO5Usd3YS0IXNMBQ/Applications-of-the-Human-Reference-Atlas?type=design&node-id=361-4247&mode=design&t=mRfBULLR11dUu5gu-4)
- Prototype Presentation: [Predict 3D Spatial Origin of Tissue Samples](https://www.figma.com/proto/sASmFJEO5Usd3YS0IXNMBQ/Applications-of-the-Human-Reference-Atlas?page-id=0%3A1&type=design&node-id=366-4352&viewport=-13647%2C113%2C0.51&t=lniGhgFlI7PQTyEW-1&scaling=scale-down&starting-point-node-id=1%3A4&show-proto-sidebar=1&mode=design)
- Prototype Presentation: [EUI Modal with Back Button
](https://www.figma.com/proto/sASmFJEO5Usd3YS0IXNMBQ/Applications-of-the-Human-Reference-Atlas?page-id=0%3A1&type=design&node-id=361-4247&viewport=-13647%2C113%2C0.51&t=lniGhgFlI7PQTyEW-1&scaling=scale-down&starting-point-node-id=1%3A4&show-proto-sidebar=1&mode=design)
## Design Notes
- Redesign context: The current implementation shows a cluttered EUI screen at the bottom of the page. Users don't have space to explore similar tissue blocks in the current implementation, as the 3D scene viewer component is squished. Additionally, the EUI does not fit into the main page container. This needs to be more responsive and less cluttered.
- The new design for this app page features two new EUI entry points:
  - Clicking the screenshot opens similar RUI locations in the EUI modal.
  - Clicking the Explore Locations button similar RUI locations in the EUI modal.
- The EUI Modal has a back button identical to the RUI Modal, in which users may press it to go back to the previous HRA Apps page.

**Comment by bhushankhope** [comment]
Fixed in PR #22
