### ISSUE TITLE
Card sizes & alignment updates

### ISSUE THREAD

**Issue by LibbyUX** [x-atlas-consortia/hra-apps#19]
# Card sizes & alignment updates
The cards on both of the results pages need minor adjustments for their sizes/alignment to provide more breathing room on the page.
## Current Implementation
![image](https://github.com/x-atlas-consortia/hra-apps/assets/97060856/fbb314d3-4c52-4030-a62e-44e8a5080fc8)

## New Specification
![image](https://github.com/x-atlas-consortia/hra-apps/assets/97060856/24e5ba7d-e4c5-4095-a0c7-c95f4720b745)

## Design Resources
- [Libby's comment in Figma for development](https://www.figma.com/file/sASmFJEO5Usd3YS0IXNMBQ?node-id=361:3842&mode=design#706772254) 
- Design File: [Improve Cell Type Annotation Card](https://www.figma.com/file/sASmFJEO5Usd3YS0IXNMBQ/Applications-of-the-Human-Reference-Atlas?type=design&node-id=361-4058&mode=design&t=2XOEqHKhcNDSHcfP-4)
- Design File: [Predict 3D Spatial Origin of Tissue Samples](https://www.figma.com/file/sASmFJEO5Usd3YS0IXNMBQ/Applications-of-the-Human-Reference-Atlas?type=design&node-id=366-4359&mode=design&t=2XOEqHKhcNDSHcfP-4)

**Comment by bhushankhope** [comment]
Fixed in PR #21
