### ISSUE TITLE
Error when using sample RUI location

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-apps#2]
On Firefox, I get an error when trying to use ```sample-kidney-registration.json```:
![image](https://github.com/x-atlas-consortia/hra-apps/assets/22821046/09947e2f-288b-437f-a6e4-dcffb661db69)

**Comment by andreasbueckle** [comment]
PS: Same issue when creating a RUI location on the spot.

**Comment by bherr2** [comment]
Should be fixed now. Had some AWS issues that caused this.
