### ISSUE TITLE
Stakeholder requirement: Annotation tools listing update

### ISSUE THREAD

**Issue by LibbyUX** [x-atlas-consortia/hra-apps#20]
# Stakeholder requirement: Annotation tools listing update

Katy needs adjustments in capitalization for the annotation tools in this interface.

Edit the "Select an annotation tool" subtext and the drop-down list:
- azimuth needs to be Azimuth
- celltypist needs to be CellTypist
- popv needs to be popV

![image](https://github.com/x-atlas-consortia/hra-apps/assets/97060856/6d2b1eee-5d87-4229-9daa-ac7bf0f5f57d)

**Comment by bhushankhope** [comment]
Fixed in PR #21
