### ISSUE TITLE
US1 - styling of RUI popup

### ISSUE THREAD

**Issue by bherr2** [x-atlas-consortia/hra-apps#4]
The Figma has RUI open in new window, but that doesn't work well. I have a popup that shows RUI now, but needs some styling around it.

![image](https://github.com/x-atlas-consortia/hra-apps/assets/34098595/6d1f827a-d736-45dd-8c27-424d7ab0aff3)

**Comment by libby-maier** [comment]
Is it possible to create a full-screen component? I'm envisioning it taking up the whole screen but some simple styling/UI to exit the demo. Ideally, this isn't a squished pop-up. Let me know. I'll work on ideas in the Figma file today.

Also, I would self-assign, but I don't have permission at the moment!

**Comment by bherr2** [comment]
Yes that's good enough. Thanks!
